server:
  port: 8761           #port for service-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false         #service registry doesen't register itself to eureka
    fetch-registry: false               #doesent fetch any registry{as this service doesen't call other services}

spring:
  application:
    name: service-registry-service
    

#service registry is case tolerant 
#When queried by the Gateway for a service named in lowercase{forced by api gateway},
#it can successfully map this to the registered service named in uppercase