server:
  port: 8083
  
spring:
  application:
    name: sequence-generator-service
  cloud:                                    #Config server => centralized server for storing all config files usually on github
    config:                                  #we are storing all config files in project folder itself so when application starts 
      enabled: false                           #it retrieves config files from project folder itself not from config server
  datasource:
    url: jdbc:mysql://localhost:3306/sequence_generator_service       #database name
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update                         #auto update/create tables
    show-sql: true                             #show sql in log
    properties:
      hibernate:
        format_sql: true                       #format sql in well readable format
        
  logging:
    level:
      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE    #method <=> URl mapping 
      org.springframework.web: TRACE            #logs entire request lifecycle{from when request hits dispatcher servlet to when response is rendered}
   

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} # Creates ID like user-service:8082
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/